### PR TITLE
Fix x64 builds of cppwinrt to properly locate the SDK

### PR DESCRIPTION
**Pull request by asklar**
https://task.ms/29349404 - The SDK sometimes stores the 64 bit location into KitsRoot10 which is wrong,
This breaks 64-bit cppwinrt.exe, so work around this by forcing to use the WoW64 hive.

### CODE REVIEW

**Review by kennykerr — APPROVED** [review]
Thanks! Did you manually verify that cppwinrt still works when the SDK is installed in the default arch location? Unfortunately, the build won't verify this.

**Comment by asklar** [comment]
> Thanks! Did you manually verify that cppwinrt still works when the SDK is installed in the default arch location? Unfortunately, the build won't verify this.

The default location is x86. The problem only occurs when trying to use **x64** cppwinrt (which is what the readme says to do). An x86 cppwinrt.exe will always use the value in the virtualized reg key under wow6432node.

Building with the cppwinrt nuget will always pick up the x86 key since the nuget package only contains the x86 cppwinrt.exe:
```
nuget pack nuget\Microsoft.Windows.CppWinRT.nuspec -Properties cppwinrt_exe=%cd%\_build\x86\Release\cppwinrt.exe;cppwinrt_fast_fwd_x86=%cd%\_build\x86\Release\cppwinrt_fast_forwarder.lib;cppwinrt_fast_fwd_x64=%cd%\_build\x64\Release\cppwinrt_fast_forwarder.lib;cppwinrt_fast_fwd_arm=%cd%\_build\arm\Release\cppwinrt_fast_forwarder.lib;cppwinrt_fast_fwd_arm64=%cd%\_build\arm64\Release\cppwinrt_fast_forwarder.lib
```

Verified that installing an old standalone SDK puts the wrong key in the native registry (and the right key in the x86 registry).

**Comment by kennykerr** [comment]
Got it. We only ship the x86 version of cppwinrt. We tend to use the x64 version for development.

**Pull request merged**
