### PR TITLE
Leverage CMake to generate project using cppwinrt

### PR DESCRIPTION
**Pull request by johanlindfors**
This sample was requested in #124 

It demonstrates a simple setup in which CMake is leveraged to generate the project structure for the IBuffer sample.

Change directory to the included output-directory and use the generate.bat script to generate solution.

Works fine on a Surface Pro 4 with Visual Studio 2017 RC and CMake 3.8.0-rc2

### CODE REVIEW

**Comment by johanlindfors** [comment]
Updated this PR to work with Creators Update.

**Comment by MathiasMagnus** [comment]
@johanlindfors @kennykerr This is a nearly 3 year old story, but why exactly was this not taken in? Honestly I'm amazed at how little CMake support core Windows-related technologies have. Large projects that would benefit the most from being able to compile on Windows with any compiler are generally committed to some build system, usually other than MSBuild.

_(Longwinded, destructive ranting on frustrations on using cross-platform tooling for Windows platform development swallowed.)_

**Comment by Sunbreak** [comment]
@MathiasMagnus 

I'm developing Flutter for Windows. Hope the snippet help

https://github.com/woodemi/quick_blue/pull/10/files

```cmake
set_target_properties(${PLUGIN_NAME} PROPERTIES
  VS_PROJECT_IMPORT ${CMAKE_BINARY_DIR}/packages/Microsoft.Windows.CppWinRT/build/native/Microsoft.Windows.CppWinRT.props
)

target_link_libraries(${PLUGIN_NAME} PRIVATE ${CMAKE_BINARY_DIR}/packages/Microsoft.Windows.CppWinRT/build/native/Microsoft.Windows.CppWinRT.targets)
```

**Comment by LBJ-the-GOAT** [comment]
> @MathiasMagnus
> 
> I'm developing Flutter for Windows. Hope the snippet help
> 
> https://github.com/woodemi/quick_blue/pull/10/files
> 
> ```cmake
> set_target_properties(${PLUGIN_NAME} PROPERTIES
>   VS_PROJECT_IMPORT ${CMAKE_BINARY_DIR}/packages/Microsoft.Windows.CppWinRT/build/native/Microsoft.Windows.CppWinRT.props
> )
> 
> target_link_libraries(${PLUGIN_NAME} PRIVATE ${CMAKE_BINARY_DIR}/packages/Microsoft.Windows.CppWinRT/build/native/Microsoft.Windows.CppWinRT.targets)
> ```

thinks man, now my project is running smoothly and very nicely because of your greate TIPS! THANK YOU!

**Comment by walbourn** [comment]
The [vcpkg](https://vcpkg.io/) manager has excellent support for CMake, so having a vcpkg port for cppwinrt might be a good solution here.

**Comment by sylveon** [comment]
There is a cppwinrt port, but the port is a no-op, so installing it and trying to use `<winrt/base.h>` makes the compiler use the Windows SDK's copy, so we just circle back to the initial problem: https://github.com/microsoft/vcpkg/blob/master/ports/cppwinrt/portfile.cmake

Ideally cppwinrt itself would have CMake stuff that allows the user to invoke the tool to generate consuming headers from the SDK and WinMD files, create WinMD files from IDL, generate source to produce a runtime component, etc. And then we'd just have the vcpkg port fetch the cppwinrt.exe tool and those CMake tasks, and CMake/vcpkg users could use those tasks in their project.

Unfortunately, just fetching the tool, generating the headers and embedding them in the vcpkg port wouldn't work too good, as not only are you limited to consuming system APIs only, but the version of the Windows SDK used by the port might not match the one used by the project (and there is nothing that can be done to adjust this from the project's side).

But it would need somebody with enough CMake knowledge to be able to invest time and resources into developing this (and my knowledge of CMake is certainly not good enough for such a task)

**Comment by walbourn** [comment]
@sylveon That's a pretty lame port, but it's better than nothing I suppose. I've authored a few ports that fetch NuGets and could be a model for the basics of how to set this up you could try starting with...

https://github.com/microsoft/vcpkg/blob/master/ports/dxsdk-d3dx

https://github.com/microsoft/vcpkg/tree/master/ports/xaudio2redist

I need to revisit the ``find_package`` implementation soon for those. If it's not addressed by then, I can take a stab at what a cppwinrt vcpkg port might look like...

**Pull request closed without merging**
