### PR TITLE
Revert nuget to 2.0.200609.3

### PR DESCRIPTION
**Pull request by kennykerr**
This is the last stable version that was ingested into the OS.

### CODE REVIEW

**Review by BenJKuhn — APPROVED** [review]

**Comment by jlaanstra** [comment]
Nothing needed to be reverted in the targets?

**Comment by jlaanstra** [comment]
This effectively blocks my team from taking newer versions as this reverts a few necessary fixes /cc @asklar. If we no longer want to maintain the build support, can we ship the build support separately so I can fork build support without needing to fork the binaries?

**Comment by kennykerr** [comment]
I don't think we can easily make further packaging changes as VS is intending to consume the package as-is, but you are free to fork the build support without needing any change from cppwinrt.  You can also just grab `cppwinrt.exe` (ignore everything else) and use your own build support. Then you're entirely independent and only rely on cppwinrt for code gen (as it should be).

**Comment by asklar** [comment]
I'm lacking some context here... What's the issue that this is unblocking/what is broken for the OS?

**Comment by jlaanstra** [comment]
@asklar this reverts also your fix for the target ordering related to accessing pdb's.

**Comment by kennykerr** [comment]
This is about reverting to a stable baseline. Since then, a few people have contributed tweaks but that resulted in a stream of regressions. I'll add you to an internal thread.

**Pull request merged**
