### PR TITLE
fix regression in nested visualizations with VS2019+

### PR DESCRIPTION
**Pull request by Scottj1s**
per advice from the VSSDK team, made sure GetChildren returns requested items, not just relying on GetItems.  (this lazy technique worked for VS2017, but does not with VS2019+)

### CODE REVIEW

**Comment by Scottj1s** [comment]
fixes #1121

**Comment by kennykerr** [comment]
The build failures seem to have started with the previous commit:

https://github.com/microsoft/cppwinrt/runs/5652229311

**Comment by Scottj1s** [comment]
> The build failures seem to have started with the previous commit:
> 
> https://github.com/microsoft/cppwinrt/runs/5652229311

but intermittently - only 1 of 3 runs has failed.  something may have changed with catch and its assumptions of CRT compat.  will investigate.

**Comment by kennykerr** [comment]
> out of disk space (sigh... PCH files).

Need modules. 😋

**Comment by Scottj1s** [comment]
Looks like catch occasionally fails with the v143 toolset - backing off for now: #1127

**Review by kennykerr — APPROVED** [review]

**Pull request merged**
