### PR TITLE
Provide the correct path to the implementation dll.

### LINKED ISSUE #449: Project references provide the wrong name for the implementation dll if the RootNamespace is different from the ProjectName.
We set the Implementation for a WinMD reference to:

```
<Implementation Condition="'$(TargetExt)' == '.dll'">$(WinMDImplementationPath)$(RootNamespace)$(TargetExt)</Implementation>
```

while it should be set to:

```
<Implementation Condition="'$(TargetExt)' == '.dll'">$(WinMDImplementationPath)$(TargetName)$(TargetExt)</Implementation>
```

### PR DESCRIPTION
**Pull request by jlaanstra**
This PR updates the path to the implementation dll for a WinMD to use ```$(TargetPath)``` instead of ```$(RootNamespace)``` which is incorrect when they differ. Also added a test project to make sure this keeps working going forward.

Fixes #449

### CODE REVIEW

**Comment by kennykerr** [comment]
Hi @jlaanstra could you resolve this branch conflict. Then we can merge into master.

**Comment by jlaanstra** [comment]
@kennykerr done.

**Comment by sylveon** [comment]
My project does not build without this PR, is there any estimate as to when I should see a release on NuGet with this fix?

**Comment by kennykerr** [comment]
@sylveon I just published 2.0.200107.1 with a rollup of fixes. 

https://www.nuget.org/packages/Microsoft.Windows.CppWinRT/

**Comment by sylveon** [comment]
This version works, thank you!

**Pull request merged**
