### PR TITLE
Define make_guid to parse string_view to guid

### PR DESCRIPTION
**Pull request by tusharpm**
- Migrate logic from `generic_types.h` (test projects) to `winrt/base.h`.
- Add `_guid` string literal wrappers.
- Support for `std::wstring_view`.
- Address `std::string_view` ->`winrt::guid` parsing in #797. A version of formatting is available in `winrt::impl::to_array`.

### CODE REVIEW

**Comment by kennykerr** [comment]
Thanks for the contribution! I'd rather be conservative and start with just a constexpr guid constructor.

**Comment by kennykerr** [comment]
Sweet thanks!

**Review by kennykerr — APPROVED** [review]
/azp run

**Comment by kennykerr** [comment]
The CI build won't run for some reason. I'll try to track that down.

**Comment by kennykerr** [comment]
@tusharpm the CI build can't seem to build the branch because it is not a local branch. Are you able to create a branch on `https://github.com/microsoft/cppwinrt`?

**Comment by tusharpm** [comment]
@kennykerr, thanks for the review and clarifying the pipeline issue. I don't have permissions to push to the upstream repo:
```
PS D:\github\cppwinrt> git branch -m user/tusharpm/make_guid
PS D:\github\cppwinrt> git push -u microsoft user/tusharpm/make_guid
remote: Permission to microsoft/cppwinrt.git denied to tusharpm.
fatal: unable to access 'https://github.com/microsoft/cppwinrt.git/': The requested URL returned error: 403
```

**Comment by kennykerr** [comment]
@tusharpm thanks for checking - I've now granted you Write access to this repo. Would you mind trying again? Hopefully that fixes it.

**Comment by tusharpm** [comment]
Continued in #833 from local branch.

**Pull request closed without merging**
