### PR TITLE
Clean output files more specific.

### LINKED ISSUE #828: Target CppWinRTClean cleans too broadly
The target
```
    <Target Name="CppWinRTClean">
        <ItemGroup>
            <_FilesToDelete Remove="@(_FilesToDelete)"/>
            <_FilesToDelete Include="$(GeneratedFilesDir)**"/>
            <_FilesToDelete Include="$(OutDir)*.winmd"/>
            <_FilesToDelete Include="$(IntDir)*.winmd"/>
            <_FilesToDelete Include="$(IntDir)*.idl"/>
            <_FilesToDelete Include="$(IntDir)*.rsp"/>
            <_FilesToDelete Include="$(CppWinRTMergedDir)**"/>
            <_FilesToDelete Include="$(CppWinRTUnmergedDir)**"/>
        </ItemGroup>
        <Delete Files="@(_FilesToDelete)"/>
    </Target>
```
in `Microsoft.Windows.CppWinRT.targets` cleans too broadly, IMHO.

It is not specifically forbidden to share the `$(OutDir)` folder between projects and we have done so. But in that case, however, the pattern `$(OutDir)*.winmd` not only cleans the merged `winmd` file of this project but also those of other projects.

That target should collect the names of the generated merged `winmd` file(s) and only delete these.

### PR DESCRIPTION
**Pull request by jlaanstra**
Fixes #828 

## Validate:

- [x] OS
- [x] Your Phone
- [x] Terminal
- [x] WinUI

### CODE REVIEW

**Comment by kennykerr** [comment]
One month check in 😉 feel free to reopen if you intend to move forward with this.

**Comment by jlaanstra** [comment]
Validation passed.

**Review by kennykerr — APPROVED** [review]

**Pull request merged**
