### PR TITLE
use app manifest

### PR DESCRIPTION
**Pull request by asklar**
In #880 we had a hacky way to enable long path support; here we do it via manifest
CC @oldnewthing

### CODE REVIEW

**Comment by kennykerr** [comment]
I don't see where you've actually backed out the undocumented API call (and #include).

**Comment by asklar** [comment]
thanks, good catch; fixed, I had messed up my clone when I migrated from my fork to the main trunk and this file hadn't gotten added.

**Review by oldnewthing — COMMENTED** [review]
Belated 👍

**Pull request merged**
