### PR TITLE
Weak references are objects too

### PR DESCRIPTION
**Pull request by oldnewthing**
If the source contributes to the module object count, then the weak reference also contributes, so that we do not unload prematurely.

Factored out module lock updating into helper base class `module_lock_updater` with specialization `update_module_lock`. This avoids a lot of code duplication.

### CODE REVIEW

**Comment by oldnewthing** [comment]
Wondering why `weak_source_producer` was defined as
```cpp
    template <bool Agile>
    struct weak_source_producer
    {
    protected:
        weak_source<Agile> m_source;
    };
```

instead of

```cpp
    template <bool Agile>
    struct weak_source_producer : protected weak_source<Agile>
    {
    };
```
This alternate definition would greatly simplify `weak_ref::that()`:

```cpp
        weak_ref<Agile>* that() noexcept
        {
            return static_cast<weak_ref<Agile>*>(this);
        }
```

**Comment by kennykerr** [comment]
@oldnewthing no particular reason - feel free to fix.

**Comment by oldnewthing** [comment]
Oh, it's because `weak_source` is final.

**Pull request merged**
