### PR TITLE
Add NuGet config

### PR DESCRIPTION
**Pull request by manodasanW**
Adding NuGet.config with public feed that upstreams to NuGet.org per guidance.

### CODE REVIEW

**Comment by sylveon** [comment]
What about external users? Since this is in the root of the repo, their Visual Studio will end up picking up this feed as well - is this intentional?

**Comment by manodasanW** [comment]
@sylveon the feed is a public externally accessible feed, so external users should have access to it.  Let me know if you don't and I can look into that.

**Comment by DefaultRyan** [comment]
It's also worth noting that all the CI tests passed, and they don't have any priveleged access to internal feeds - the CI tests can only access public feeds just like external users.

**Review by DefaultRyan — APPROVED** [review]

**Comment by sylveon** [comment]
Ah, fair enough then

**Comment by walbourn** [comment]
Note that another solution would be to not have a `nuget.config` at all and use in YAML:

```
  - task: NuGetCommand@2
    displayName: NuGet restore
    inputs:
      solution: cppwinrt.sln
      feedRestore: $(GUID_FEED)
      includeNuGetOrg: false
```
   
The `GUID_FEED` is set as a variable so it only gets used by ADO pipelines and not everyone else. GitHub Actions can just use nuget.org directly.

**Pull request merged**
