### PR TITLE
Fix cyclic dependency error when upgrading VS 2022

### PR DESCRIPTION
**Pull request by DefaultRyan**
This will help prevent [this error](https://developercommunity.visualstudio.com/t/Unable-to-update-from-Preview-11-to-Pre/1476321) from happening in the future. #960 should be fully working after this.

### CODE REVIEW

**Review by kennykerr — APPROVED** [review]

**Comment by raffaeler** [comment]
@DefaultRyan 
Is this already on the marketplace?
I tested it today on VS2022 Preview 3.1 and still get the error

**Comment by LanceMcCarthy** [comment]
Confirmed still seeing this (attempted install yesterday) 

image

**Comment by sylveon** [comment]
See https://github.com/microsoft/cppwinrt/issues/960#issuecomment-908558849

VS 2022 Preview 4 isn't out yet

**Comment by Bluesman74** [comment]
The preview is out, but the Extension still doesn't work 
WinRT_BadVersion

**Comment by raffaeler** [comment]
Same here.
I tested it today on VS2022 Preview 4 and still get the same error

**Comment by ericjpeters** [comment]
It looks like there was a fix merged into master, but as of 09/22/2021 / VS2022 Preview 4.1, I'm still getting the same error.

**Pull request merged**
