### PR TITLE
to_message() function extracts exception text from catch(...)

### PR DESCRIPTION
**Pull request by oldnewthing**
Handy for logging. This complements to_hresult().

### CODE REVIEW

**Comment by kennykerr** [comment]
Is the intention to log an error message and then proceed in cases where an exception is otherwise ignored?

**Comment by oldnewthing** [comment]
Yeah, it's common to catch all errors, log it, and then move on. Whether it's advisable is another matter, but it's a common pattern, and too often people just catch `hresult_error` and forget to catch `std::exception` so they end up missing standard exceptions, most notably `std::bad_alloc` (which is what `E_OUTOFMEMORY` projects to).

**Comment by kennykerr** [comment]
Cool. And the motivation to add another WIL hook?

**Review by kennykerr — APPROVED** [review]
Oh to support custom exception types.

**Comment by kennykerr** [comment]
So for some reason, the CI build won't build anything other than local branches. I trust you've fully tested this, but next time please use a local branch on https://github.com/microsoft/cppwinrt.

**Pull request merged**
