### PR TITLE
Add GitHub Action build and test workflow

### PR DESCRIPTION
**Pull request by alvinhochun**
This is *not* intended to be a replacement to the Azure build, but as a supplemental build. The added workflow performs builds and runs tests on x86 and x64, and also tries to build the nuget package.

### CODE REVIEW

**Comment by kennykerr** [comment]
I forget the magical incantation to get GitHub to notice there's a new workflow in a PR... 🤔

**Comment by sylveon** [comment]
Should we try at least building the tests on ARM64?

**Comment by kennykerr** [comment]
> I forget the magical incantation to get GitHub to notice there's a new workflow in a PR... 🤔

It might not run until the workflow is in master, in which case we can just merge and then validate with a subsequent PR to test the workflow. 

> Should we try at least building the tests on ARM64?

Does GitHub support ARM64 builds now?

**Comment by sylveon** [comment]
The CI image is shared with Microsoft hosted pipeline agents, and it has the ARM64 cross compiler installed. It's not an ARM64 machine though, so we can only try building the tests as basic sanity check, can't actually run them.

**Comment by kennykerr** [comment]
Got it, yes that's all the Azure build does as well.

**Comment by kennykerr** [comment]
@alvinhochun I enabled GitHub Actions on this repo after you created this PR, so I think you just need to push another commit to trigger the new workflow to run.

**Comment by riverar** [comment]
@sylveon This isn't related to the PR here but just a heads up, Microsoft has private ARM64 runners in ADO.

**Comment by sylveon** [comment]
Yeah I heard about it but I'm not in the preview

**Comment by alvinhochun** [comment]
The workflow is being prevented from running: https://github.com/microsoft/cppwinrt/actions/runs/3252917426

> actions/checkout@v3 is not allowed to be used in microsoft/cppwinrt. Actions in this workflow must be: within a repository that belongs to your Enterprise account or matching the following: actions/checkout@v2, actions/upload-artifact@v3.

**Comment by kennykerr** [comment]
I updated it to allow `actions/checkout@v3` but will have to be restarted somehow...

**Comment by alvinhochun** [comment]
Pushed again and now they're running.

**Comment by kennykerr** [comment]
Woohoo - now we need Clang and GNU workflows. 😜

**Review by kennykerr — APPROVED** [review]
Thanks!

**Comment by kennykerr** [comment]
@alvinhochun the actions seem a little unreliable: 

https://github.com/microsoft/cppwinrt/actions/runs/3267768111/jobs/5373367929

Rerunning often seems to fix them, but it would be nice to track down what's causing the frequent failures.

**Comment by kennykerr** [comment]
Never mind - this is another case of #1202 - be nice if the error was easier to see tho 😜

**Comment by kennykerr** [comment]
Sounds great!

**Pull request merged**
