### PR TITLE
Better support for mingw-w64 and GCC-compatible compilers

### PR DESCRIPTION
**Pull request by alvinhochun**
There are still some intrinsics and defines missing in mingw-w64 (see https://github.com/mstorsjo/llvm-mingw/issues/307) which can all be replaced with other compatible constructions. Verified by compiling a sample program locally for i686, x86_64 and aarch64 (aarch64 build is untested because I don't have a compatible system).

(CI checks for mingw-w64 will be coming soon™)

CC: @mstorsjo @cristianadam

### CODE REVIEW

**Comment by kennykerr** [comment]
I'm not familiar with the GCC intrinsics. Does someone else want to take a stab at reviewing this? @DefaultRyan @oldnewthing

**Review by BenJKuhn — APPROVED** [review]
I can't speak to the completeness of these changes wrt to making mingw work, but the changes themselves seem correct based on a close reading. The use of __iso_volatile_load64 for the MSVC implementation is to avoid a perf hit due to MS-specific behavior described here: https://learn.microsoft.com/en-us/cpp/build/reference/volatile-volatile-keyword-interpretation?view=msvc-170. It should be unnecessary in MinGW, though if it adds the same memory barriers MS does for volatile reads, it may incur a perf penalty. I couldn't find a quick answer to that. It'll be correct and usable though either way.

**Pull request merged**
