### PR TITLE
Return the full path to the generated WinMD.

### LINKED ISSUE #809: [Regression] Resolving metadata fails when referencing a C++/WinRT project from a C# UWP project
_Original issue opened by @matthew4850 in https://github.com/dotnet/msbuild/issues/5412_

Since CppWinRT nuget version `2.0.191023.3`, generating the appxbundle of C# UWP project consuming a CppWinRT component fails because of a `Metadata file [path] could not be found` error.

See https://github.com/dotnet/msbuild/issues/5412 for further details and a sample solution to repro the issue.

Note: here are the results using different releases of CppWinRT nuget:
| CppWinRT nuget release | Issue does repro? |
|:-:|:-:|
| Microsoft.Windows.CppWinRT.2.0.191018.6 | No |
| Microsoft.Windows.CppWinRT.2.0.191023.3 | Yes |
| Microsoft.Windows.CppWinRT.2.0.200316.3 | Yes |
| Microsoft.Windows.CppWinRT.2.0.201113.7<br/>(current latest release) | Yes |

### PR DESCRIPTION
**Pull request by jlaanstra**
This PR fixes a bug in the GetResolvedWinMD target that causes a relative path to be returned by the Build target causing problems when the target started the build tries to resolve the output.

Fixes #809 and https://github.com/dotnet/msbuild/issues/5412

## Validate:

- [x] OS
- [x] Your Phone
- [x] Terminal
- [x] WinUI

### CODE REVIEW

**Review by Scottj1s — APPROVED** [review]
Thanks for the ongoing cppwinrt build support!

**Review by ChrisGuzak — APPROVED** [review]

**Comment by jlaanstra** [comment]
Completed validation.

**Review by kennykerr — APPROVED** [review]
Thanks!

**Comment by kennykerr** [comment]
Queued build 2.0.201217.4

**Pull request merged**
