### PR TITLE
Avoid code repetition in resumable_io::start and resumable_io::start_pending

### PR DESCRIPTION
**Pull request by AlexBAV**
Separate `resumable_io::start_pending` method is no longer required; `resumable_io::start` is now capable of working with both callbacks returning `void` and `bool`. Also avoids code repetition.

`start_pending` is left for compatibility though (implemented via a call to `resumable_io::start`).

### CODE REVIEW

**Comment by kennykerr** [comment]
We cannot directly accept pull requests at the moment since the headers are generated by the C++/WinRT compiler. Even the base.h header is an amalgamation produced by this compiler. Still, we’ll take a look at the pull request and see if we can include it in a future update. Thanks for the feedback!

**Comment by kennykerr** [comment]
I had a look at your suggested changes. I like the idea of combining both methods into a single start method that can handle both scenarios. We will make this available in a future update. Thanks for the feedback!

**Comment by AlexBAV** [comment]
Thanks, Kenny.

BTW, I wonder if it is legal at all to cancel a callback if Windows IO function completes synchronously. It appears that if the handle notification mode is not set to `FILE_SKIP_COMPLETION_PORT_ON_SUCCESS` (see <https://msdn.microsoft.com/en-us/library/windows/desktop/aa365538(v=vs.85).aspx>), it would be an error to do so.

It looks like the start_pending is only for those handles for which this notification mode is set. What do you think of it?

**Comment by kennykerr** [comment]
Yes, the thread pool callback must be canceled if the I/O completes synchronously *and* the completion packet will not be queued. This is only the case if the FILE_SKIP_COMPLETION_PORT_ON_SUCCESS mode is set and why I originally had both start and start_pending. The implementation needs to handle this carefully to avoid leaks.

**Comment by AlexBAV** [comment]
Thnk you for clarification.

**Pull request closed without merging**
