### PR TITLE
Use / for include paths, not \

### PR DESCRIPTION
**Pull request by LegalizeAdulthood**
I was an MVP for Direct3D for 10 years, you might already have a CLA on file for me...

### CODE REVIEW

**Comment by raffaeler** [comment]
I believe it does not make sense to make pull requests on the libraries as it is all generated code.
The patch should be always applied to the generator.

**Comment by BrentRe** [comment]
Actually this particular request is to update the Sample projects, which are not generated code.

**Comment by raffaeler** [comment]
oops, sorry

**Comment by LegalizeAdulthood** [comment]
Yes, as @BrentRe pointed out, the libraries are fine, it's just the sample code that is using \ instead of /.

They also use `#pragma lib`, which isn't portable C++, but noone else besides Windows has a WinRT runtime anyway, so I doubt that part really matters.

**Comment by BrentRe** [comment]
We could move the #pragma lib into the VC++ project settings to remove it. But as all these samples are Windows-specific, I'm not sure there's much benefit. The reasoning for putting in the source code was to alert developers that Windows Store applications must link with that library. Something that's easily missed when it buried in a linker command line setting.

For the record, what are you suggesting to change from back slashes to forward slashes? I'm guessing because both work and forward is more platform agnostic... I'm not pushing back but these samples are very Windows specific (as is C++/WinRT currently).

**Comment by kennykerr** [comment]
Thanks for the contribution Richard!

**Pull request merged**
